name: MyFirstWorkFlows
on: push
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Creating a report file
        run: echo "This is my first GitHub Actions workflow!" > report.txt
       
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report.txt
          path: report.txt
      
  my_second_job:
    needs: my_first_job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: report.txt
      - name: Check content
        run: cat report.txt



      
        